# This file contains parameter for several test controllers, which will be uploaded to the ros parameter server via
# the roslaunch file
motor0:
  id: 0
  joint_name: motor0
  type: roboy_controller/PositionController

motor1:
  id: 1
  joint_name: motor1
  type: roboy_controller/PositionController

motor2:
  id: 2
  joint_name: motor2
  type: roboy_controller/PositionController

motor3:
  id: 3
  joint_name: motor3
  type: roboy_controller/PositionController

motor4:
  id: 4
  joint_name: motor4
  type: roboy_controller/PositionController

motor5:
  id: 5
  joint_name: motor5
  type: roboy_controller/PositionController

motor6:
  id: 6
  joint_name: motor6
  type: roboy_controller/PositionController

motor7:
  id: 7
  joint_name: motor7
  type: roboy_controller/PositionController

motor8:
  id: 8
  joint_name: motor8
  type: roboy_controller/PositionController

motor9:
  id: 9
  joint_name: motor9
  type: roboy_controller/PositionController

motor10:
  id: 10
  joint_name: motor10
  type: roboy_controller/PositionController

motor11:
  id: 11
  joint_name: motor11
  type: roboy_controller/PositionController

motor12:
  id: 12
  joint_name: motor12
  type: roboy_controller/PositionController

motor13:
  id: 13
  joint_name: motor13
  type: roboy_controller/PositionController

motor14:
  id: 14
  joint_name: motor14
  type: roboy_controller/PositionController

motor15:
  id: 15
  joint_name: motor15
  type: roboy_controller/PositionController

motor16:
  id: 16
  joint_name: motor16
  type: roboy_controller/PositionController

motor17:
  id: 17
  joint_name: motor17
  type: roboy_controller/PositionController

motor18:
  id: 18
  joint_name: motor18
  type: roboy_controller/PositionController

motor19:
  id: 19
  joint_name: motor19
  type: roboy_controller/PositionController

motor20:
  id: 20
  joint_name: motor20
  type: roboy_controller/PositionController

motor21:
  id: 21
  joint_name: motor21
  type: roboy_controller/PositionController

motor22:
  id: 22
  joint_name: motor22
  type: roboy_controller/PositionController

motor23:
  id: 23
  joint_name: motor23
  type: roboy_controller/PositionController
